### ISSUE TITLE
Fixes Needed

### ISSUE THREAD

**Issue by kcraath** [Topl/Topl-ico#2]
**Changes**
1. Capital letters on the front page - lower cased - no screaming
2. Font change asap - Make this similar to what we have on website or just **sans serif** (don't ever use serif for presentation in websites)
3. The ICO status bar - maybe have a number out of total (no preference here)
4.  Font size above buttons smaller - this is making scroll function on my page 
5.  Buttons should look like buttons and not just rectangles with text in (**please** change this)
 
![edits](https://user-images.githubusercontent.com/33494767/46909163-8e9f9d00-cef3-11e8-8f3c-6bedf10c3f55.png)

**Comment by scasplte2** [comment]
Incomplete information
![image](https://user-images.githubusercontent.com/1753335/46910120-b1867d00-cf04-11e8-8039-9fcb268a8c02.png)

3. Should query min and max amounts and list (or just state them, they are 1000 and 1,000,000
4. "check balance by going here'" is static and doesn't go anywhere.

The calculator page also needs to be explained. It is not obvious what it is right now. 

Shouldn't say "Do not forget to add the gas", should read like "When setting up your transaction to the Topl presale contract we recommend a gas limit of 250,000 to avoid an out of gas exception"

**Comment by scasplte2** [comment]
Tweaked up the website and submitted a pull request on commit c8ebf724428ecc484db8676efc5eb7a59974338f

Currently pushed to website and trying to resolve CSS issue that remains.
